In [1]:
import numpy as np
import pandas as pd
from Q_learning import Qlearning
from Agent_Stats import Agent_Stats
from Agent_Q import AgentQ

In [2]:
states = np.array([0, 1, 2, 3])
actions = np.array([0, 1])
a1 = AgentQ(states, actions, 0)
a2 = AgentQ(states, actions, 0)
q_l = Qlearning((a1, a2), learning_rate=1.0, discount_factor=0.95, iter=300000)
q_l.run_multiple_iterated_games(100)

Running game 1 of 100
Running game 2 of 100
Running game 3 of 100
Running game 4 of 100
Running game 5 of 100
Running game 6 of 100
Running game 7 of 100
Running game 8 of 100
Running game 9 of 100
Running game 10 of 100
Running game 11 of 100
Running game 12 of 100
Running game 13 of 100
Running game 14 of 100
Running game 15 of 100
Running game 16 of 100
Running game 17 of 100
Running game 18 of 100
Running game 19 of 100
Running game 20 of 100
Running game 21 of 100
Running game 22 of 100
Running game 23 of 100
Running game 24 of 100
Running game 25 of 100
Running game 26 of 100
Running game 27 of 100
Running game 28 of 100
Running game 29 of 100
Running game 30 of 100
Running game 31 of 100
Running game 32 of 100
Running game 33 of 100
Running game 34 of 100
Running game 35 of 100
Running game 36 of 100
Running game 37 of 100
Running game 38 of 100
Running game 39 of 100
Running game 40 of 100
Running game 41 of 100
Running game 42 of 100
Running game 43 of 100
Running game 44 of 100
Running game 45 of 100
Running game 46 of 100
Running game 47 of 100
Running game 48 of 100
Running game 49 of 100
Running game 50 of 100
Running game 51 of 100
Running game 52 of 100
Running game 53 of 100
Running game 54 of 100
Running game 55 of 100
Running game 56 of 100
Running game 57 of 100
Running game 58 of 100
Running game 59 of 100
Running game 60 of 100
Running game 61 of 100
Running game 62 of 100
Running game 63 of 100
Running game 64 of 100
Running game 65 of 100
Running game 66 of 100
Running game 67 of 100
Running game 68 of 100
Running game 69 of 100
Running game 70 of 100
Running game 71 of 100
Running game 72 of 100
Running game 73 of 100
Running game 74 of 100
Running game 75 of 100
Running game 76 of 100
Running game 77 of 100
Running game 78 of 100
Running game 79 of 100
Running game 80 of 100
Running game 81 of 100
Running game 82 of 100
Running game 83 of 100
Running game 84 of 100
Running game 85 of 100
Running game 86 of 100
Running game 87 of 100
Running game 88 of 100
Running game 89 of 100
Running game 90 of 100
Running game 91 of 100
Running game 92 of 100
Running game 93 of 100
Running game 94 of 100
Running game 95 of 100
Running game 96 of 100
Running game 97 of 100
Running game 98 of 100
Running game 99 of 100
Running game 100 of 100
Done!

In [3]:
q_l.agents_stats[0].turn_chosen_actions_comb_into_states(q_l.agents_stats[1])
df = q_l.agents_stats[0].turn_into_dataframe(option=0)

In [4]:
q_l.agents_stats[0].chosen_actions

array([[1., 1., 0., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 1., 1., 1.]])

In [5]:
df.head()

,Round 0,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6,Round 7,Round 8,Round 9,...,Round 299990,Round 299991,Round 299992,Round 299993,Round 299994,Round 299995,Round 299996,Round 299997,Round 299998,Round 299999
0,3.0,3.0,1.0,2.0,3.0,3.0,3.0,2.0,1.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
1,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
2,0.0,1.0,0.0,2.0,0.0,1.0,1.0,1.0,0.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
3,2.0,2.0,2.0,1.0,0.0,2.0,2.0,0.0,0.0,2.0,...,0.0,3.0,0.0,3.0,0.0,3.0,0.0,3.0,0.0,3.0
4,2.0,2.0,2.0,1.0,1.0,0.0,1.0,0.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [6]:
last_100_columns = list(df.columns[-100:])
df_last_100 = df[last_100_columns]
df_last_100

,Round 299900,Round 299901,Round 299902,Round 299903,Round 299904,Round 299905,Round 299906,Round 299907,Round 299908,Round 299909,...,Round 299990,Round 299991,Round 299992,Round 299993,Round 299994,Round 299995,Round 299996,Round 299997,Round 299998,Round 299999
0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
1,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
2,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
3,0.0,3.0,0.0,3.0,0.0,3.0,0.0,3.0,0.0,3.0,...,0.0,3.0,0.0,3.0,0.0,3.0,0.0,3.0,0.0,3.0
4,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
96,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
97,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [7]:
df_last_100[df_last_100[df_last_100 == 3].count(axis=1) == 100]

,Round 299900,Round 299901,Round 299902,Round 299903,Round 299904,Round 299905,Round 299906,Round 299907,Round 299908,Round 299909,...,Round 299990,Round 299991,Round 299992,Round 299993,Round 299994,Round 299995,Round 299996,Round 299997,Round 299998,Round 299999
0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
1,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
2,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
4,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
6,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
95,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
96,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
97,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
99,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [8]:
df_last_100[df_last_100[df_last_100 == 0].count(axis=1) == 100]

,Round 299900,Round 299901,Round 299902,Round 299903,Round 299904,Round 299905,Round 299906,Round 299907,Round 299908,Round 299909,...,Round 299990,Round 299991,Round 299992,Round 299993,Round 299994,Round 299995,Round 299996,Round 299997,Round 299998,Round 299999
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df_last_100[(df_last_100[df_last_100 == 0].count(axis=1) == 50) & (df_last_100[df_last_100 == 1].count(axis=1) == 50)]

Empty DataFrame
Columns: [Round 299900, Round 299901, Round 299902, Round 299903, Round 299904, Round 299905, Round 299906, Round 299907, Round 299908, Round 299909, Round 299910, Round 299911, Round 299912, Round 299913, Round 299914, Round 299915, Round 299916, Round 299917, Round 299918, Round 299919, Round 299920, Round 299921, Round 299922, Round 299923, Round 299924, Round 299925, Round 299926, Round 299927, Round 299928, Round 299929, Round 299930, Round 299931, Round 299932, Round 299933, Round 299934, Round 299935, Round 299936, Round 299937, Round 299938, Round 299939, Round 299940, Round 299941, Round 299942, Round 299943, Round 299944, Round 299945, Round 299946, Round 299947, Round 299948, Round 299949, Round 299950, Round 299951, Round 299952, Round 299953, Round 299954, Round 299955, Round 299956, Round 299957, Round 299958, Round 299959, Round 299960, Round 299961, Round 299962, Round 299963, Round 299964, Round 299965, Round 299966, Round 299967, Round 299968, Round 299969, Round 299970, Round 299971, Round 299972, Round 299973, Round 299974, Round 299975, Round 299976, Round 299977, Round 299978, Round 299979, Round 299980, Round 299981, Round 299982, Round 299983, Round 299984, Round 299985, Round 299986, Round 299987, Round 299988, Round 299989, Round 299990, Round 299991, Round 299992, Round 299993, Round 299994, Round 299995, Round 299996, Round 299997, Round 299998, Round 299999]
Index: []

[0 rows x 100 columns]